<a href="https://colab.research.google.com/github/shethisha1312-jpg/labwork/blob/main/8.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

arr1 = np.random.randint(1,100,size=(3,3))
arr1

arr2 = np.random.randint(1,100,size=(3,3))
arr2

print("Array 1:\n",arr1)
print("Array 2:\n",arr2)

print("Addition :\n",arr1 + arr2)
print("Subtraction :\n",arr1 - arr2)
print("Multiplication :\n",arr1 * arr2)
print("Division :\n",arr1 / arr2)



Array 1:
 [[24 22  7]
 [63 62 58]
 [97  4 53]]
Array 2:
 [[98 38  7]
 [81 32 41]
 [60 59 74]]
Addition :
 [[122  60  14]
 [144  94  99]
 [157  63 127]]
Subtraction :
 [[-74 -16   0]
 [-18  30  17]
 [ 37 -55 -21]]
Multiplication :
 [[2352  836   49]
 [5103 1984 2378]
 [5820  236 3922]]
Division :
 [[0.24489796 0.57894737 1.        ]
 [0.77777778 1.9375     1.41463415]
 [1.61666667 0.06779661 0.71621622]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [ ]:
arr = np.random.randint(1,10,3)
arr

print("orignal array:",arr)
print("Squere root :",np.sqrt(arr))
print("Exponential :",np.exp(arr))
print("Logarithm:",np.log(arr))


orignal array: [6 3 6]
Squere root : [2.44948974 1.73205081 2.44948974]
Exponential : [403.42879349  20.08553692 403.42879349]
Logarithm: [1.79175947 1.09861229 1.79175947]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [ ]:
import numpy as np

arr = np.array([0,30,45,70,90])

radians = np.radians(arr)

print("Orignal Array:",arr)
print("Sin:",np.sin(radians))
print("Cos:",np.cos(radians))
print("Tan:",np.tan(radians))



Orignal Array: [ 0 30 45 70 90]
Sin: [0.         0.5        0.70710678 0.93969262 1.        ]
Cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 3.42020143e-01
 6.12323400e-17]
Tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 2.74747742e+00
 1.63312394e+16]


##### 4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [ ]:
arr = np.array([10,20,30,40,50])

mean = np.mean(arr)
std = np.std(arr)

normalized = (arr - mean)/std

print("Original Array:",arr)
print("Mean:",mean)
print("Standared Deviation:",std)
print("Normalized Array:",normalized)

Original Array: [10 20 30 40 50]
Mean: 30.0
Standared Deviation: 14.142135623730951
Normalized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [ ]:
def euclidean_distance(point1,point2):

  point1 = np.array(point1)
  point2 = np.array(point2)

  distance = np.sqrt(np.sum((point1 - point2) ** 2))

  return distance

p1 = [2,3]
p2 = [5,7]

result = euclidean_distance(p1,p2)
print("Euclidean Distance:",result)



Euclidean Distance: 5.0


#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

horizontal = np.concatenate((arr1,arr2))

vertical = np.concatenate((arr1,arr2))

print("Array1:",arr1)
print("Array2:",arr2)

print("Horizontal Concatention:",horizontal)
print("Vertical Concatention:",vertical)


Array1: [1 2 3]
Array2: [4 5 6]
Horizontal Concatention: [1 2 3 4 5 6]
Vertical Concatention: [1 2 3 4 5 6]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [12]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

v_stack = np.vstack((arr1 , arr2))
h_stack = np.hstack((arr1,arr2))

print("Vertical Stack:\n",v_stack)
print("Horizontal Stack:\n",h_stack)

v_split = np.vsplit(v_stack,2)

print("Vertical Split:\n",v_split)

h_split = np.hsplit(h_stack,2)

print("Horizontal Split:\n",h_split)




Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Split:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Horizontal Split:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [14]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])

sub_arrays = np.vsplit(arr, 4)

print("Original Array:\n ",arr)

print(" 4 Equal Sub-arrays:\n")

for i in sub_arrays:

    print(i)

Original Array:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 4 Equal Sub-arrays:

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]


##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [15]:


arr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

print("Original 3D Array:",arr)

flat_array = arr.flatten()

print("\nFlattened Array:",flat_array)

reshaped_array = flat_array.reshape(2, 2, 2)

print("\nReshaped Array:",reshaped_array)


Original 3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Flattened Array: [1 2 3 4 5 6 7 8]

Reshaped Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [19]:


arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

concatenate = np.concatenate((arr1, arr2), axis=0)

stack = np.stack((arr1, arr2), axis=0)

hstack = np.hstack((arr1, arr2))

print("Array 1:\n",arr1)

print("Array 2:\n",arr2)

print("Concatenate:\n",concatenate)

print("Stack:\n",stack)

print("Hstack:\n",hstack)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenate:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Hstack:
 [[1 2 5 6]
 [3 4 7 8]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [20]:

arr = np.array([10, 25, 5, 40, 15])

max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Array:", arr)
print("Index of Maximum Element:", max_index)
print("Index of Minimum Element:", min_index)

Array: [10 25  5 40 15]
Index of Maximum Element: 3
Index of Minimum Element: 2


##### 2. Sort a 2D array along different axes and display the result.

In [22]:


arr = np.array([[30, 10, 20],
                  [60, 40, 50],
                  [90, 70, 80]])

print("Original Array:\n",arr)

sort_axis0 = np.sort(arr, axis=0)

sort_axis1 = np.sort(arr, axis=1)

print("\nSorted along Axis 0:\n",sort_axis0)

print("\nSorted along Axis 1:\n",sort_axis1)


Original Array:
 [[30 10 20]
 [60 40 50]
 [90 70 80]]

Sorted along Axis 0:
 [[30 10 20]
 [60 40 50]
 [90 70 80]]

Sorted along Axis 1:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

In [23]:

arr = np.random.randint(1, 50, 10)

print("Random Array:", arr)


print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Random Array: [ 5 44 45 26 31 25 49 24 49 19]
Mean: 31.7
Median: 28.5
Variance: 193.81
Standard Deviation: 13.921566003866088


##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

In [24]:


arr = np.array([10, 25, 5, 40, 15, 30])

threshold = 20

result = np.where(arr > threshold)

print("Array:", arr)
print("Elements greater than", threshold, ":", arr[result])
print("Their indexes:", result)

Array: [10 25  5 40 15 30]
Elements greater than 20 : [25 40 30]
Their indexes: (array([1, 3, 5]),)


##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [25]:

arr = np.array([10, -5, 0, 8, -2, 0, 15, -7])

positive = np.sum(arr > 0)
negative = np.sum(arr < 0)
zero = np.sum(arr == 0)

print("Array:", arr)
print("Positive elements:", positive)
print("Negative elements:", negative)
print("Zero elements:", zero)

Array: [10 -5  0  8 -2  0 15 -7]
Positive elements: 3
Negative elements: 3
Zero elements: 2
