<a href="https://colab.research.google.com/github/shethisha1312-jpg/labwork/blob/main/8.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Task 1.1: Basic Filtering**
#### Create a NumPy array `ages` with the following values: `[25, 30, 18, 35, 22, 40, 17]`.
#### Use boolean indexing to create a new array `adults` containing only the ages that are 18 or older.


### **Task 1.2: Filtering with Multiple Conditions**
#### Using the `ages` array again, find the ages that are strictly greater than 20 AND strictly less than 35.
#### Store the result in a new array called `young_adults`.


### **Task 1.3: Filtering Strings**
#### Create a NumPy array `names` with the following values: `['Alice', 'Bob', 'Charlie', 'David', 'Eve']`.
#### Use boolean indexing to select names that start with the letter 'A' or 'E'.
#### Hint: You might need to use string operations within your boolean condition.

---

### **Task 2.1: Basic Masking for Selection**
#### Create a NumPy array `temperatures` with the following values: `[28, 32, 25, 35, 30, 22, 38]`.
#### Create a boolean mask `is_hot` where `True` indicates temperatures above 30 degrees Celsius.
#### Use this mask to select the hot temperatures from the `temperatures` array.


### **Task 2.2: Masking for Modification**
#### Using the `temperatures` array again, use the `is_hot` mask to change all temperatures above 30 degrees Celsius to 31 degrees Celsius.


### **Task 2.3: Using `np.where()` for Masking**
#### Create a NumPy array `scores` with the following values: `[65, 80, 72, 90, 55, 78]`.
#### Use `np.where()` to create a new array `grades`. If a score is 75 or above, the grade should be 'Pass', otherwise 'Fail'.

---

### **Task 3.1: Reshaping a 1D array to 2D**
#### Create a 1D NumPy array `numbers_1d` with values from 1 to 12 (inclusive).
#### Reshape this array into a 2D array with 3 rows and 4 columns.

### **Task 3.2: Reshaping a 2D array to 1D (Flattening)**
#### Using the `numbers_2d` array from the previous task, flatten it back into a 1D array.

### **Task 3.3: Reshaping with `-1`**
#### Create a 1D NumPy array `values` with values from 1 to 15 (inclusive).
#### Reshape this array into a 2D array with 5 rows, letting NumPy automatically determine the number of columns.

---

### **Task 4.1: Broadcasting a Scalar to an Array**
#### Create a NumPy array `prices` with the following values: `[10, 20, 30]`.
#### Increase all prices by 5 using broadcasting.

### **Task 4.2: Broadcasting a 1D Array to a 2D Array (Row-wise)**
#### Create a 2D NumPy array `sales` representing sales figures for 3 products over 2 days:
#### ```
#### [[10, 20],
####  [15, 25],
####  [12, 18]]
#### ```
#### Create a 1D NumPy array `bonuses` representing bonuses for each product: `[2, 3, 1]`.
#### Add the `bonuses` array to the `sales` array, broadcasting row-wise.


### **Task 4.3: Broadcasting a 1D Array to a 2D Array (Column-wise)**
#### Using the `sales` array again, create a 1D NumPy array `tax_rates` representing tax rates for each day: `[0.1, 0.05]`.
#### Calculate the tax amount for each sale by multiplying the `sales` array with the `tax_rates` array, broadcasting column-wise.

In [12]:
# task 1.1

import numpy as np

ages = np.random.randint(1,30,6)


adult = ages [ages >= 18]

print("Ages : ",ages)
print("Adults:",adult)



Ages :  [ 6  7  1 22  8 10]
Adults: [22]


In [7]:
# task 1.2

ages = np.random.randint(1,40,6)

young_adult = ages[(ages > 20) & (ages < 35)]

print("Ages:",ages)
print("Young Adults:",young_adult)


Ages: [ 4 12  9 28 27 29]
Young Adults: [28 27 29]


In [8]:
# task 1.3

names  = np.array(['Alice','Bob','Chatlie','David','Eve'])

selected_names = names[np.char.startswith(names,'A') | np.char.startswith(names,'E')]

print("Selected Names :",selected_names)



Selected Names : ['Alice' 'Eve']


In [9]:
# task 2.1

temperatures = np.array([28,32,25,35,30,22,38])

is_hot = temperatures > 30

hot_temperatures = temperatures[is_hot]

print("Bollean Mask :",is_hot)
print("Hot Tempernatures :",hot_temperatures)



Bollean Mask : [False  True False  True False False  True]
Hot Tempernatures : [32 35 38]


In [10]:
# task 2.2
temperatures = np.array([28,32,25,35,30,22,38])

is_hot = temperatures > 30
temperatures[is_hot] = 31

print("Updates Teperatures:",temperatures)

Updates Teperatures: [28 31 25 31 30 22 31]


In [11]:
#task 2.3

scores = np.array([65, 80, 72, 90, 55, 78])

greads = np.where(scores >= 75,"Pass","Fail")

print("Scores :",scores)
print("Gread :",greads)


Scores : [65 80 72 90 55 78]
Gread : ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [14]:
# task 3.1

num_1d = np.arange(1,13)

num_2d = num_1d.reshape(3,4)

print("1D Array :",num_1d)
print("2D Array:\n",num_2d)



1D Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# 3.2

num_2d = np.random.randint(1,13,size=(3,4))

num_1d_arr = num_2d.flatten()

print("1D Array :",num_1d_arr)

1D Array : [10 12  3  4  3  3  1 11  9  9 10  6]


In [21]:
# task 3.3

val = np.arange(1,16)

values_2d = val.reshape(5,-1)

print("2D Array:\n ",values_2d)
print("Shape of new array :",values_2d.shape)


2D Array:
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Shape of new array : (5, 3)


In [25]:
# task 4.1

import numpy as np

price = np.array([10,20,30])

new_price = price + 5

print("New Price :",new_price)


New Price : [15 25 35]


In [27]:
# task 4.2

sales = np.array([[10,20],[30,40],[50,60]])

bonuses = np.array([2,3,1])

new_sales = sales + bonuses.reshape(3,1)

print("New sales:\n",new_sales)

New sales:
 [[12 22]
 [33 43]
 [51 61]]


In [29]:
# task 4.3

sales = np.array([[10,20],[15,25],[12,18]])

tax_rates = np.array([0.1 , 0.05])

tax_amount = sales * tax_rates

print("Tax Amount:\n ",tax_amount)







Tax Amount:
  [[1.   1.  ]
 [1.5  1.25]
 [1.2  0.9 ]]
