<a href="https://colab.research.google.com/github/shethisha1312-jpg/labwork/blob/main/Lab_Work_8_1_%7C_Python_AI_ML_DA_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Introduction to NumPy**

#### **Task 1**: Import the NumPy library and print its version.

In [53]:
import numpy as np
print(np.__version__)

2.1.3


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [57]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [58]:
array = np.random.rand(3,4)
print(array)
print("Shape: ",array.shape)
print("Data Type:",array.dtype)


[[0.50787403 0.47579411 0.03255375 0.66040036]
 [0.37734169 0.90435916 0.6171402  0.43046059]
 [0.04472422 0.14457257 0.06650044 0.16359967]]
Shape:  (3, 4)
Data Type: float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [60]:
num = np.linspace(0,50,3)
num


array([ 0., 25., 50.])

**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [61]:
# using list
list1 = [1,2,3,4]
list2 = [1,2,3,4]
result = list1 + list2
print("Addition of list(Concatation): ",result)

# using numpy array
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
result = array1 +array2
print("Addition of array(Elementwise):",result)


Addition of list(Concatation):  [1, 2, 3, 4, 1, 2, 3, 4]
Addition of array(Elementwise): [ 6  8 10 12]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [62]:
array = np.zeros((3,4),dtype=int)
array


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [63]:
array = np.ones((2,5),dtype=float)
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [64]:
array = np.arange(10,51,5)
array


array([10, 15, 20, 25, 30, 35, 40, 45, 50])

**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [65]:
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [66]:
array = np.random.randint(1,21,size=(4,4))
array

array([[ 3,  2, 12, 18],
       [ 8,  5, 17, 10],
       [ 6, 18,  9, 19],
       [15,  1,  4, 18]])

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [67]:
array = np.arange(1,16)
print("Array:",array)
extract_array = array[2:8]
print("Extrct Array:")
print(extract_array)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Extrct Array:
[3 4 5 6 7 8]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [69]:
array = np.arange(1,10)
array2 = array.reshape((3,3))
print(array2[1][2])

6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [70]:
array = np.arange(1,17)
print("Array:",array)
array1 = array.reshape((4,4))
print("Array1:")
print(array1)
array3 = array1[-2:,-2:]
print("Array3:")
print(array3)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Array1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array3:
[[11 12]
 [15 16]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [71]:
array = np.random.randint(10,50,size=(5,5))
print("Origial matrix:")
print(array)

array[0,:]=100
print("Modified matrix:")
print(array)

Origial matrix:
[[39 34 15 44 25]
 [19 25 47 31 18]
 [24 46 36 30 16]
 [37 40 21 24 28]
 [26 21 21 45 29]]
Modified matrix:
[[100 100 100 100 100]
 [ 19  25  47  31  18]
 [ 24  46  36  30  16]
 [ 37  40  21  24  28]
 [ 26  21  21  45  29]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [72]:
array = np.arange(1,11)
print(array)
filterd_array = array[array<=5]
print(filterd_array)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
